version: '3'
services:
  web:
    container_name: burlyed_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${DOCKER_WEB_PORT}:8080'
    volumes:
      - .:/usr/local/burlyed
    env_file:
      - '.env.docker'
    depends_on:
      - db 
      - redis 
    tty: true
  db:
    container_name: burlyed_db
    build:
      context: .
      dockerfile: dockerfile.db
    ports:
      - '${DOCKER_POSTGRES_PORT}:5432'
    volumes:
      - /usr/local/postgres:/var/lib/postgressql/data
    env_file:
      - '.env.docker'
  redis:
    image: redis:4.0-alpine
    container_name: burlyed_redis
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    volumes:
      - /usr/local/redis:/data
        